### PR TITLE
faster webpack build using happy pack

### PR DESCRIPTION
**Pull request by byumark**

### CODE REVIEW

**Comment by tuxsudo** [comment]
awesome! @eatrocks will test and merge ASAP. Thanks @byumark !

**Comment by eatrocks** [comment]
Thanks for the PR @byumark . I'll need to give this a whirl in Windows :( since the author [mentions](https://github.com/amireh/happypack#does-it-work-under-windows) a couple of outstanding Windows issues, [#70](https://github.com/amireh/happypack/issues/70) and [#99](https://github.com/amireh/happypack/issues/99).  As much as we prefer to work on a Mac we currently need this starter to work in Windows too. Downloading VM image now.

**Comment by eatrocks** [comment]
We aren't experiencing those happypack issues...  [#70](https://github.com/amireh/happypack/issues/70) and [#99](https://github.com/amireh/happypack/issues/99)
So this PR is cleared for merge. **THANKS for the PR!**

**Comment by eatrocks** [comment]
Timing on an `npm run build`...
16.7 seconds without happypack (first and subsequent runs)
13.9 seconds first run with happypack
9.3 seconds subsequent runs with happypack
These are on my 1.5 year old MBP. Quick tests without proper controls.

**Comment by byumark** [comment]
The biggest difference I noticed was with npm run dev...

**Comment by byumark** [comment]
The biggest difference I noticed was with `npm run dev`...

**Comment by eatrocks** [comment]
I was too lazy to get out a stopwatch to time `npm run dev`. I simply ran `time npm run build` which won't work with `npm run dev` because that task doesn't end until you kill it.

**Comment by byumark** [comment]
I counted in my head and it went from about 30 seconds to about 10.

**Pull request merged**
